// Measured wire sizes, as `cosechat sizes` prints them (the Python reference
// embeds the same table in SPEC.md §14; a test checks that both agree).
// Every size is a whole packet as it goes on a road (no road auth); "frames"
// is how many RNode frames (508 bytes) it takes after fragmentation.

import { BytesMap } from './bytes.js'
import { Identity, SUITES } from './identity.js'
import * as L from './link.js'
import * as M from './message.js'
import { ANNOUNCE, DATA, FRAGMENT_OVERHEAD, LINK_ACCEPT, LINK_DATA, LINK_REQUEST, Packet, RECEIPT, fragment } from './packet.js'
import { newRatchet } from './ratchet.js'
import * as R from './resource.js'

export const LORA_MTU = 508
const SEQUENCE = 1790000000000
const TEXT = 'hello, how are you?'
const zeros = (n) => new Uint8Array(n)

export function frames(packet, mtu = LORA_MTU) {
  return packet.length <= mtu ? 1 : fragment(packet, mtu - FRAGMENT_OVERHEAD).length
}

export function measure(suite) {
  const [a, b] = [Identity.generate(suite), Identity.generate(suite)]
  const [ra, rb] = [newRatchet(a.kemAlg), newRatchet(b.kemAlg)]
  const out = { keyset: a.publicBytes.length }
  const pkt = (kind, payload, dest = a.address) => new Packet(kind, 0, dest, null, payload).encode()
  const args = { appData: new Map([['name', 'alice']]), sequence: SEQUENCE }
  out['full announce'] = pkt(ANNOUNCE, M.makeAnnounce(a, ra, { ...args, full: true }))
  out['short announce'] = pkt(ANNOUNCE, M.makeAnnounce(a, ra, { ...args, full: false }))
  const rks = new BytesMap()
  rks.set(b.address, rb.public())
  const { sealed, message } = M.seal(a, [b.public()], { content: TEXT, ratchets: rks, receiptSecret: zeros(16) })
  out.message = pkt(DATA, sealed, b.address)
  const tag = M.receiptTag(message.receiptSecret, b.address)
  out.receipt = pkt(RECEIPT, new Uint8Array([...tag, ...zeros(8)]))
  const pending = L.makeRequest(a, b.public(), rb.public())
  out['link request'] = pkt(LINK_REQUEST, pending.request, b.address)
  const { accept, keys: kb } = L.acceptRequest(b, pending.request, () => a.public(), [rb], false)
  out['link accept'] = pkt(LINK_ACCEPT, accept)
  out['link message'] = pkt(LINK_DATA, L.seal(kb, L.messageBody({ content: TEXT, receiptSecret: zeros(16) })))
  const part = R.encode(R.R_PART, [zeros(16), 0, zeros(R.PART_SIZE)])
  out['resource part'] = pkt(LINK_DATA, L.seal(kb, part))
  return out
}

const n = (x) => x.toLocaleString('en-US')

export function table() {
  const rows = Object.fromEntries(Object.keys(SUITES).map((s) => [s, measure(s)]))
  const suites = Object.keys(rows)
  const lines = ['| | ' + suites.map((s) => `\`${s}\``).join(' | ') + ' |', '|---|' + '---:|'.repeat(suites.length)]
  for (const kind of Object.keys(rows[suites[0]])) {
    const cells = suites.map((s) => {
      const v = rows[s][kind]
      if (typeof v === 'number') return `${n(v)} B`
      const f = frames(v)
      return `${n(v.length)} B` + (f > 1 ? ` (${f} frames)` : '')
    })
    lines.push(`| ${kind} | ${cells.join(' | ')} |`)
  }
  lines.push('')
  lines.push(`Whole packets without road auth; "frames" = RNode frames of ${LORA_MTU} bytes after fragmentation. Messages carry the ${TEXT.length}-character text "${TEXT}" and a receipt secret. Generated by \`cosechat sizes\`.`)
  return lines.join('\n')
}
